const rawExamData = [
    // ==========================================
    // BÀI ĐỌC SỐ 1: Tyche Fine Carpets
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>TYCHE FINE CARPETS — Pleiades Collection</b><br><br><b>Product Availability (updated daily)</b><table border='1' cellpadding='8' style='border-collapse: collapse; width: 100%; margin: 15px 0; text-align: center; background-color: #fff;'><tr><th style='background-color: #f0f0f0;'>Name</th><th style='background-color: #f0f0f0;'>Size (cm)</th><th style='background-color: #f0f0f0;'>Shipping Weight</th><th style='background-color: #f0f0f0;'>Quantity Available (today)</th><th style='background-color: #f0f0f0;'>Quantity Available (in 30 days)</th><th style='background-color: #f0f0f0;'>Quantity Available (in 60 days)</th></tr><tr><td>Artemis</td><td>190 x 280</td><td>13 kg</td><td>30</td><td>60</td><td>0</td></tr><tr><td>Hera</td><td>190 x 280</td><td>14 kg</td><td>16</td><td>20</td><td>0</td></tr><tr><td>Janus</td><td>160 x 230</td><td>11 kg</td><td>0</td><td>0</td><td>20</td></tr><tr><td>Iris</td><td>120 x 170</td><td>9 kg</td><td>10</td><td>15</td><td>15</td></tr></table>",

            "<b>E-mail</b><br><b>To:</b> Frieda Zuckerman<br><b>From:</b> Miles Sorrell<br><b>Date:</b> February 5<br><b>Subject:</b> Logistical arrangements<br><b>Attachment:</b> 8 Photos<br><br>Dear Ms. Zuckerman:<br><br>I regret to inform you that Tyche Fine Carpets, the supplier we selected for the carpets in The Pavel Hotel's lobby and lounge areas, will not have our chosen pattern available until well after the hotel's anticipated opening date of March 1. Attached are photographs of several alternative selections that I believe will work well with the décor. They are all made of the same material as the previous selection, and the prices are comparable. With the grand opening less than a month away, I need a decision from you as soon as possible. Even with this last-minute change, I am certain that The Pavel Hotel will provide the ambience we have set out to create.<br><br>Thank you,<br>Miles Sorrell",

            "<b>Pavel Hotel Open</b><br><b>by Lavonne Coe</b><br><br>(Centerville—March 2) Former city court judge Mildred Simpson joined owner Patrice Snell yesterday to celebrate the opening of The Pavel Hotel in downtown Centerville, between the library and the visitors center. Once the city's courthouse and Ms. Simpson's workplace, the existing structure had been vacant for the past nine years. Now the space boasts 34 elegant rooms, an inviting lounge with a fireplace, and a gorgeous lobby. An on-site café is expected to open next month. The interior, designed by Miles Sorrell, retains the old features of the building, such as expansive windows and high ceilings, while creating a warm and inviting space."
        ],
        questions: [
            { text: "What does the chart indicate about all the carpets in the Pleiades Collection?", options: { A: "They will be available in 60 days.", B: "They are currently in stock.", C: "They have different weights.", D: "They are the same size." }, correct: "C", explanation: "Bảng liệt kê cân nặng (Shipping Weight) của 4 loại thảm lần lượt là 13kg, 14kg, 11kg, 9kg -> Chúng có cân nặng khác nhau." },
            { text: "What carpet did Mr. Sorrell originally order?", options: { A: "Artemis", B: "Hera", C: "Janus", D: "Iris" }, correct: "C", explanation: "Email thông báo thảm đã chọn sẽ KHÔNG có sẵn cho đến sau ngày khai trương (1/3). Nhìn vào bảng, chỉ có mẫu 'Janus' là hôm nay (0) và 30 ngày tới (0) không có hàng, phải đợi tới 60 ngày." },
            { text: "What does Mr. Sorrell ask Ms. Zuckerman to do?", options: { A: "Delay the hotel's opening", B: "Select a substitute item", C: "Order some different furniture", D: "Send photographs of the lobby" }, correct: "B", explanation: "Miles gửi kèm ảnh các mẫu thay thế và yêu cầu Zuckerman đưa ra quyết định sớm -> Chọn một sản phẩm thay thế (substitute item)." },
            { text: "According to the article, what occupied the building prior to The Pavel Hotel?", options: { A: "A library", B: "A visitors center", C: "A courthouse", D: "A café" }, correct: "C", explanation: "Bài báo đề cập tòa nhà này từng là 'city's courthouse' (tòa án thành phố)." },
            { text: "What is indicated about The Pavel Hotel?", options: { A: "It opened on schedule.", B: "It was under construction for nine years.", C: "It is becoming a tourist destination.", D: "It was not affected by the carpet delay." }, correct: "A", explanation: "Email dự kiến ngày khai trương là 1/3. Bài báo viết ngày 2/3 xác nhận khách sạn đã khai trương vào 'yesterday' (hôm qua) -> Khai trương đúng lịch trình." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 2: Mumbai Canning Ltd.
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>E-mail 1</b><br><b>To:</b> a.raman@bgi.co.in<br><b>From:</b> s.kapoor@mail.co.in<br><b>Date:</b> 15 April<br><b>Subject:</b> Thank-you note<br><br>Dear Mr. Raman,<br><br>Thanks for encouraging me to apply for the position at Neela Advertising and for writing such a glowing referral on my behalf. Mr. Nirmal, Neela’s chief recruiting officer, expressed his admiration for the television commercials I produced for Delhi Works, but he explained that his company in fact needs someone who can also create Web content and applications. I was therefore not offered the position.<br><br>Kindly let me know if you happen to hear of any other positions that might be a good fit for me. Thank you in advance.<br><br>Best regards,<br>Shreya",

            "<b>Letter</b><br>17 May<br>Shreya Kapoor<br>21 Hammam Street<br>Mumbai<br><br>Dear Ms. Kapoor,<br><br>I am pleased that you will be joining Mumbai Canning Ltd. on 1 June. I was impressed with the knowledge you displayed at the time you interviewed at our offices. Your specific experience at Delhi Works, Inc., will be of tremendous value here.<br><br>I am enclosing some documents that you should complete, sign, and bring with you when you report to Human Resources at 9:30 A.M. on your first day. You will receive a brief administrative orientation at that time. Your assigned mentor, Ms. Meera Sethi, will meet you there at 10:30 to escort you to your department, where she will review your training plan and the projects the team is currently working on. At noon she will be taking you to our cafeteria for lunch in the company of some of your colleagues. I hope to join you there as well.<br><br>Welcome to Mumbai Canning Ltd.!<br><br>Sincerely,<br>Zara Mehta<br>Mumbai Canning Ltd.",

            "<b>E-mail 2</b><br><b>To:</b> a.raman@bgi.co.in<br><b>From:</b> s.kapoor@mail.co.in<br><b>Date:</b> 20 May<br><b>Subject:</b> Good news<br><br>Dear Mr. Raman,<br><br>Thank you for your last referral. The director offered me the position during our interview, and I will be starting on 1 June. I will be happy to provide you with details about my duties once I get settled.<br><br>Best,<br>Shreya"
        ],
        questions: [
            { text: "Why was Ms. Kapoor turned down for a position at Neela Advertising?", options: { A: "She failed to provide adequate referrals.", B: "She did not meet the criteria for the job.", C: "She missed the application deadline.", D: "She was not available for a follow-up interview." }, correct: "B", explanation: "Email 1 cho biết công ty Neela Advertising cần người có khả năng tạo nội dung Web, nên cô ấy không được nhận việc -> Không đáp ứng được tiêu chí công việc." },
            { text: "What is suggested about Ms. Kapoor?", options: { A: "She left her job at Delhi Works, Inc., several years ago.", B: "She used to work with Mr. Nirmal at Delhi Works, Inc.", C: "She will produce television commercials for Mumbai Canning Ltd.", D: "She has recently switched careers." }, correct: "C", explanation: "Email 1 nhắc đến việc cô sản xuất quảng cáo truyền hình (television commercials) cho Delhi Works. Thư mời làm việc (Letter) nhấn mạnh kinh nghiệm tại Delhi Works sẽ cực kỳ giá trị tại đây -> Gợi ý rằng cô sẽ tiếp tục sản xuất quảng cáo cho công ty mới." },
            { text: "Who most likely is Ms. Sethi?", options: { A: "A cafeteria manager", B: "A payroll accountant", C: "A marketing team member", D: "A budget director" }, correct: "C", explanation: "Sethi là người hướng dẫn (mentor) của Kapoor và sẽ xem xét các dự án nhóm đang làm. Vì Kapoor chuyên làm quảng cáo, cô thuộc đội marketing, suy ra Sethi cũng là thành viên đội marketing." },
            { text: "According to the letter, where will Ms. Mehta be at noon on June 1?", options: { A: "In a design meeting", B: "On a business trip", C: "At a job interview", D: "At a dining facility" }, correct: "D", explanation: "Mehta viết trong thư: 'At noon she will be taking you to our cafeteria for lunch... I hope to join you there as well.' -> Bà ấy sẽ có mặt ở nhà ăn (dining facility) vào buổi trưa." },
            { text: "How was Ms. Kapoor offered her new job?", options: { A: "In person", B: "In a letter", C: "By e-mail", D: "Over the telephone" }, correct: "A", explanation: "Trong Email 2, Kapoor viết: 'The director offered me the position during our interview' -> Cô được mời nhận việc ngay trong buổi phỏng vấn (tức là gặp mặt trực tiếp - In person)." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 3: Greenville focus group
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>E-mail 1</b><br><b>To:</b> Kate Millerson<br><b>From:</b> Daniel Friedman<br><b>Date:</b> January 25<br><b>Subject:</b> Upcoming focus group<br><br>Hi, Kate,<br><br>The next focus group to test the new fruit-flavored beverage ideas will be held on February 1 in the Greenville office. Mari Kobayashi will be leading it.<br><br>Please design a questionnaire to collect the group’s feedback using the one you created last month as a template and send it over to Mari. After the focus group takes place, please tally the results in the form of a chart. I need to incorporate this information into my monthly report to the chief marketing officer.<br><br>Thanks,<br>Daniel",

            "<b>E-mail 2</b><br><b>To:</b> Daniel Friedman<br><b>From:</b> Kate Millerson<br><b>Date:</b> February 3<br><b>Subject:</b> Results of Greenville focus group<br><b>Attachment:</b> 1 Greenville Results<br><br>Hi, Daniel,<br><br>According to Mari Kobayashi, 25 of the 30 registered participants for Greenville took the taste test and completed the questionnaire. The results are mostly in line with the results from last month’s focus group. However, Mari did note that the Greenville group’s most popular flavor was unexpected.<br><br>Per your request, the tabulated results are attached. Please let me know if you will need additional information for your report to Ms. Acosta or if she wants to see the comments on the questionnaires.<br><br>Kate",

            "<b>Greenville Focus Group</b><br><b>February 1</b><br><br><i>(Numbers indicate how many participants preferred each option.)</i><br><br><b>Type of drink</b><br>Carbonated: (8) | Noncarbonated: (17)<br><br><b>Highest price willing to pay</b><br>$1.25: (5) | $1.50: (12) | $2.00: (5) | $2.50: (3)<br><br><b>Flavor</b><br>Cherry: (2) | Lemon: (7) | Lime: (13) | Orange: (3)"
        ],
        questions: [
            { text: "In the first e-mail, what is indicated about Ms. Millerson?", options: { A: "She has designed questionnaires before.", B: "She will lead a focus group on February 1.", C: "She will interview Ms. Kobayashi.", D: "She has been transferred to the Greenville office." }, correct: "A", explanation: "Daniel dặn cô dùng bảng khảo sát mà cô đã tạo tháng trước làm mẫu ('using the one you created last month as a template') -> Cô ấy từng thiết kế bảng khảo sát trước đây." },
            { text: "What does Mr. Friedman say he will do with Ms. Millerson’s data?", options: { A: "Distribute it to his staff", B: "Show it to a new client", C: "Include it in a report", D: "Write an article based on it" }, correct: "C", explanation: "Daniel viết: 'I need to incorporate this information into my monthly report' -> Đưa dữ liệu vào báo cáo hàng tháng." },
            { text: "Who most likely is Ms. Acosta?", options: { A: "The director of Human Resources", B: "The chief marketing officer", C: "A focus group leader", D: "An information technology expert" }, correct: "B", explanation: "Trong Email 2, Kate nhắc đến báo cáo gửi cho Ms. Acosta. Đối chiếu Email 1, Daniel nói phải làm báo cáo gửi cho 'chief marketing officer' -> Suy ra Acosta là Giám đốc Marketing." },
            { text: "What does Ms. Millerson suggest about the Greenville focus group?", options: { A: "Some people arrived late.", B: "The group will meet again soon.", C: "Each attendee received a payment.", D: "There were fewer participants than expected." }, correct: "D", explanation: "Email 2 ghi '25 of the 30 registered participants... took the taste test' -> Chỉ có 25/30 người đăng ký tham gia -> Ít người tham gia hơn mong đợi." },
            { text: "Which flavor preference surprised Ms. Kobayashi?", options: { A: "Cherry", B: "Lemon", C: "Lime", D: "Orange" }, correct: "C", explanation: "Email 2 nhắc đến việc hương vị được yêu thích nhất (most popular flavor) gây bất ngờ. Nhìn vào bảng kết quả, vị Lime (Chanh) có nhiều người chọn nhất (13 người) -> Đó chính là vị gây bất ngờ." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 4: Software training
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>E-mail 1</b><br><b>To:</b> All Staff<br><b>From:</b> Leila Hedlund<br><b>Subject:</b> November software training<br><b>Date:</b> October 30<br><b>Attachment:</b> 1 Software Training Schedule<br><br>Dear Staff,<br><br>Throughout November, we will be holding mandatory training sessions for two of our major software products.<br><br>Training in the Abacus Deepthink software will be required for all staff members and can be completed in a single online session. Several possible session times are available. The software has gone through several changes recently, so even longtime users must attend.<br><br>The Optisafe software training will be offered in person and is a requirement only for Drug Safety department members. This past year, major upgrades have been made to the software, and all department staff will need to learn how to use its new capabilities.<br><br>Please look over the attached schedule and go to the company training Web site to sign up.<br><br>Thank you,<br>Leila Hedlund",

            "<b>Kodarex Pharmaceuticals</b><br><b>Software Training Schedule</b><table border='1' cellpadding='8' style='border-collapse: collapse; width: 100%; margin: 15px 0; text-align: center; background-color: #fff;'><tr><th style='background-color: #f0f0f0;'>Date</th><th style='background-color: #f0f0f0;'>Title</th><th style='background-color: #f0f0f0;'>Time</th><th style='background-color: #f0f0f0;'>Location</th></tr><tr><td>November 6</td><td>Abacus Deepthink</td><td>9 A.M.–11 A.M.</td><td>Online</td></tr><tr><td>November 9</td><td>Optisafe</td><td>9 A.M.–1 P.M.</td><td>Building C, Room 822</td></tr><tr><td>November 14</td><td>Abacus Deepthink</td><td>1 P.M.–3 P.M.</td><td>Online</td></tr><tr><td>November 17</td><td>Abacus Deepthink</td><td>10 A.M.–12 P.M.</td><td>Online</td></tr><tr><td>November 22</td><td>Optisafe</td><td>1 P.M.–5 P.M.</td><td>Building C, Room 822</td></tr><tr><td>November 27</td><td>Abacus Deepthink</td><td>3 P.M.–5 P.M.</td><td>Online</td></tr></table>",

            "<b>E-mail 2</b><br><b>To:</b> Leila Hedlund<br><b>From:</b> Diego Ramos-Toro<br><b>Re:</b> November software training<br><b>Date:</b> October 31<br><br>Dear Leila,<br><br>I need to attend both software trainings, but I had planned to take off work from November 6 through November 18. Also, I must attend an all-day client meeting on November 22 that we cannot reschedule. Will there be any alternative sessions for the Optisafe training that I could attend?<br><br>Thank you,<br>Diego Ramos-Toro"
        ],
        questions: [
            { text: "According to the first e-mail, what is true about the Optisafe software?", options: { A: "It is replacing another software program.", B: "It is used for data analysis.", C: "It has undergone significant updates.", D: "It is the focus of monthly trainings." }, correct: "C", explanation: "Đoạn 3 của Email 1 nhắc đến Optisafe: 'major upgrades have been made to the software' -> Đã trải qua những cập nhật đáng kể." },
            { text: "According to the schedule, what do the Abacus Deepthink trainings have in common?", options: { A: "They are given on the same day of the month.", B: "They are taught by the same instructor.", C: "They are delivered through a Web site.", D: "They all start at the same time." }, correct: "C", explanation: "Nhìn vào cột Location trên lịch trình, tất cả các buổi đào tạo Abacus Deepthink đều được ghi là 'Online' -> Đào tạo qua trang web." },
            { text: "Why did Mr. Ramos-Toro write to Ms. Hedlund?", options: { A: "To register for a training session", B: "To ask for help resolving a conflict", C: "To report a software malfunction", D: "To request additional time off" }, correct: "B", explanation: "Diego viết email để nhờ sắp xếp lại vì lịch học phần mềm Optisafe bị trùng với lịch nghỉ phép và lịch họp khách hàng của anh ấy -> Yêu cầu giúp giải quyết sự xung đột lịch trình." },
            { text: "What is suggested about Mr. Ramos-Toro?", options: { A: "He works in the Drug Safety department.", B: "He completed a required training.", C: "He is Ms. Hedlund’s supervisor.", D: "He wants an alternative position in the company." }, correct: "A", explanation: "Trong Email 2, Diego nói anh ấy phải học cả 2 phần mềm. Email 1 ghi rõ Optisafe 'is a requirement only for Drug Safety department members' -> Suy ra anh ấy làm ở phòng An toàn Thuốc." },
            { text: "When will Mr. Ramos-Toro most likely complete a training?", options: { A: "On November 14", B: "On November 17", C: "On November 22", D: "On November 27" }, correct: "D", explanation: "Diego nghỉ phép từ 6 đến 18/11 nên bỏ lỡ các buổi học Abacus ngày 6, 14, 17. Anh ấy bận họp ngày 22. Vậy lịch học Abacus duy nhất còn lại để anh ấy tham gia là vào ngày 27/11." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 5: Linton Business Alliance
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>E-mail 1</b><br><b>To:</b> Linton Business Alliance members<br><b>From:</b> Robin Fowler<br><b>Date:</b> June 12<br><b>Subject:</b> Organizational meeting<br><b>Attachment:</b> 1 Proposed agenda<br><br>Hello everyone,<br><br>I am reaching out to determine when we can meet. Since news about the creation of our Business Alliance is generating interest within the community, it is time to create some written materials to promote ourselves.<br><br>I would like to spend time at our meeting formulating an action plan for soliciting members. I have attached a draft agenda. It should not take long to coordinate our assignments for speaking to local business owners, but we could probably save meeting time by doing this online before the meeting.<br><br>Please send me an e-mail with your availability for the next few weeks. I understand that Sasha Zimmer is out of town until early July, but I still hope we can find a meeting date and time that will work for everyone.<br><br>Robin Fowler",

            "<b>Organizational meeting — Proposed agenda</b><br><br><b>10:00 A.M.</b> — Introductions<br><b>10:15 A.M.</b> — Item 1: Discussion to define mission statement and identify three initiatives for the year<br><b>11:00 A.M.</b> — Item 2: Media training workshop with Brandon Clark*<br><b>12:00 noon</b> — Item 3: Assign tasks for creation of Alliance communications: press release, letter to local business owners, brochure, and a Web page highlighting membership<br><b>12:30 P.M.</b> — Item 4: Assign Alliance members to speak with business owners<br><b>12:45 P.M.</b> — Adjourn<br><br><i>*Brandon Clark, a news anchor at the Ulani News Network, has offered to lead a workshop about interacting with the media. He will emphasize the importance of preparing talking points and staying on message.</i>",

            "<b>E-mail 2</b><br><b>To:</b> Linton Business Alliance members<br><b>From:</b> Robin Fowler<br><b>Date:</b> June 22<br><b>Subject:</b> Finalized organizational meeting<br><b>Attachment:</b> 1 Final agenda<br><br>Thanks to everyone for your feedback. The final agenda is attached. We have confirmed the workshop for June 28 at the Linton Community Library. The library opens at 10:00 A.M., and staff will be on hand to help set up the room.<br><br>I’d like to stress the importance of sticking to the agenda because our time together is limited. Those meeting participants who would like to discuss any topics further can perhaps enjoy some lunch after the meeting. I will plan to go to Devon’s Sandwich Shop, which is just one block south of the library. All are welcome to join me.<br><br>Robin Fowler"
        ],
        questions: [
            { text: "Based on the first e-mail, what is most likely true about the Linton Business Alliance?", options: { A: "It opposes a city policy.", B: "It is a new organization.", C: "It charges membership fees.", D: "It is led by city officials." }, correct: "B", explanation: "Email 1 nhắc đến 'creation of our Business Alliance' (sự thành lập Liên minh của chúng ta) và đây là cuộc họp 'Organizational' (tổ chức ban đầu) -> Đây là một tổ chức mới." },
            { text: "What item does Ms. Fowler suggest could be removed from the proposed agenda?", options: { A: "Item 1", B: "Item 2", C: "Item 3", D: "Item 4" }, correct: "D", explanation: "Trong Email 1, cô ấy viết 'coordinate our assignments for speaking to local business owners... save meeting time by doing this online' -> Mục này tương ứng với Item 4 trên lịch trình." },
            { text: "What does the proposed agenda indicate about Mr. Clark?", options: { A: "He is applying for membership.", B: "He will be a guest speaker.", C: "He is a retired journalist.", D: "He will take notes during a discussion." }, correct: "B", explanation: "Phần ghi chú cuối lịch trình viết rằng Brandon Clark sẽ 'lead a workshop' (dẫn dắt hội thảo) -> Ông ấy sẽ là một diễn giả khách mời." },
            { text: "What can be concluded about the upcoming meeting?", options: { A: "It will be open to the general public.", B: "It will receive significant media attention.", C: "It will be missing at least one group member.", D: "It will require attendees to bring some equipment." }, correct: "C", explanation: "Email 1 báo Sasha Zimmer đi vắng đến đầu tháng 7. Email 2 chốt lịch họp vào ngày 28/6. Suy ra Sasha sẽ không thể tham dự cuộc họp này." },
            { text: "In the second e-mail, what information about lunch does Ms. Fowler provide?", options: { A: "The time of a reservation", B: "The number of attendees", C: "The cost", D: "The location" }, correct: "D", explanation: "Cô ấy rủ mọi người ăn trưa tại 'Devon’s Sandwich Shop' -> Cung cấp thông tin về địa điểm (location)." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 6: Elvinna’s
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>Brochure</b><br><b>Elvinna’s</b><br><br>Located just outside of Nassau, the capital city of The Bahamas, Elvinna’s is the ideal venue for your reception, banquet, or business meeting. Away from the hustle and bustle of the city, it is surrounded by lush gardens featuring a variety of beautiful sculptures.<br><br>The Alameda Room seats between 100 and 250 people comfortably, and our largest space, the Bougainvillea Room, is perfect for up to 300 guests. For business meetings, the Tamarind Room can accommodate up to 50 guests, while the Waterfall Room, slightly larger, seats up to 80 people. Our two business meeting spaces are outfitted with the latest technology to support productive and efficient meetings.<br><br>Our elegant restaurant, the Candlewood Tree, offers an ample menu that takes into account many dietary restrictions and preferences. Plan ahead to join us on July 10 when we offer a special Independence Day dinner menu!<br><br>To book an event, visit elvinnas.bs. First-time reservations for select dates receive a 15 percent discount. For further information call 242-555-0135.",

            "<b>E-mail 1</b><br><b>To:</b> Tanika Nichols<br><b>From:</b> Brian Darville<br><b>Date:</b> 18 February<br><b>Subject:</b> Anniversary planning<br><br>Hello, Tanika,<br><br>I visited Elvinna’s and looked at the space that you suggested might be right for our company’s anniversary celebration. Their catering menu would suit the various preferences of our expected guests, now numbering over 250. Currently the room is available on two Saturdays, 15 July and 5 August; it is also available on Wednesday, 23 August. Note that this last date would qualify for a nice discount.<br><br>Let me know if I have your approval to book this room. We need to make a decision quickly before other parties reserve those dates. I’ll be in touch soon about rescheduling the awards ceremony in May.<br><br>Brian",

            "<b>E-mail 2</b><br><b>To:</b> Brian Darville<br><b>From:</b> Tanika Nichols<br><b>Date:</b> 18 February<br><b>Subject:</b> Anniversary planning<br><br>Hello, Brian,<br><br>Thank you for the information about Elvinna’s. Let’s take advantage of that discount date they are offering. It may help us stay within our budget. Please contact them to make the reservation.<br><br>Tanika Nichols, Senior Vice President<br>Nassau Telecommunications"
        ],
        questions: [
            { text: "What does the brochure mention about Elvinna’s?", options: { A: "It is able to host groups of various types.", B: "It is conveniently located in downtown Nassau.", C: "It has hired a new chef for its restaurant.", D: "It plans to renovate a business center." }, correct: "A", explanation: "Tờ rơi quảng cáo đây là địa điểm lý tưởng cho 'reception, banquet, or business meeting' (tiệc chiêu đãi, tiệc lớn, hoặc họp doanh nghiệp) -> Có khả năng tổ chức cho nhiều loại nhóm khác nhau." },
            { text: "What does Mr. Darville indicate about the plan for his company’s celebration?", options: { A: "It should feature a simple menu.", B: "It will need to be rescheduled.", C: "It will include an awards ceremony.", D: "It is a decision he cannot make alone." }, correct: "D", explanation: "Trong Email 1, Brian viết: 'Let me know if I have your approval to book this room' -> Anh ấy cần sự phê duyệt của sếp chứ không thể tự quyết định một mình." },
            { text: "Where will the company’s anniversary celebration most likely be held?", options: { A: "In the Alameda Room", B: "In the Bougainvillea Room", C: "In the Tamarind Room", D: "In the Waterfall Room" }, correct: "B", explanation: "Trong Email 1, Brian nhắc đến lượng khách là 'over 250' (hơn 250 người). Đối chiếu với Tờ rơi, chỉ có Bougainvillea Room sức chứa lên tới 300 người mới đủ chỗ (Alameda tối đa chỉ 250)." },
            { text: "Why is Mr. Darville concerned?", options: { A: "Not enough people have responded to an invitation.", B: "He thinks that a different venue might cost less.", C: "A venue that he likes might be reserved by another group.", D: "He has not been able to secure entertainment." }, correct: "C", explanation: "Brian giục sếp: 'We need to make a decision quickly before other parties reserve those dates' -> Lo sợ địa điểm bị nhóm khác đặt mất." },
            { text: "When will Nassau Telecommunications’ celebration most likely take place?", options: { A: "On July 10", B: "On July 15", C: "On August 5", D: "On August 23" }, correct: "D", explanation: "Ở Email 2, sếp Tanika quyết định chọn ngày được giảm giá ('take advantage of that discount date'). Ở Email 1, Brian cho biết ngày được giảm giá là 23 tháng 8." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 7: Cardiology conference
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>E-Mail Message</b><br><b>To:</b> Andrea Williams &lt;a.williams@cardiocentre.co.uk&gt;<br><b>From:</b> Samuel Penfold &lt;s.penfold@cardiocentre.co.uk&gt;<br><b>Date:</b> 2 August<br><b>Subject:</b> Re: Cardiology conference<br><br>Dear Dr. Williams,<br><br>Yes, I will be going to the cardiology conference, and I am looking forward to it. Unfortunately, I will not be able to travel there with you because I am seeing patients until 3 P.M. on 5 August. I will have to miss the first day’s sessions, but I will be on-site that evening and for the next two days.<br><br>Maybe we can have dinner together one evening? Evrim Turgut was telling me about your research together into diagnostic imaging technologies, and I would love the chance to discuss it with you.<br><br>Let me know when you will be free.<br><br>All best,<br>Samuel Penfold, MD",

            "<b>NTS Rail Ticket</b><br><br><b>Train Number:</b> EX111<br><b>Reservation:</b> 4JK5 4RN5 4XW8<br><b>Class:</b> STANDARD<br><b>Date:</b> 5 AUGUST<br><b>Passenger:</b> ANDREA WILLIAMS<br><b>Adult:</b> ONE<br><b>Price:</b> £18.00<br><b>Return Trip:</b> NOT INCLUDED<br><b>From:</b> LANCASTER<br><b>Seat Number:</b> NONE ASSIGNED<br><i>Printed on 1 August</i><br><b>To:</b> MANCHESTER<br><b>Fare:</b> ADVANCE PURCHASE",

            "<b>Train Schedule — NTS Rail</b><br><b>Lancaster to Manchester</b><table border='1' cellpadding='8' style='border-collapse: collapse; width: 100%; margin: 15px 0; text-align: center; background-color: #fff;'><tr><th style='background-color: #f0f0f0;'>Train Number</th><th style='background-color: #f0f0f0;'>Departure Time</th><th style='background-color: #f0f0f0;'>Duration</th><th style='background-color: #f0f0f0;'>Arrival Time</th><th style='background-color: #f0f0f0;'>Price</th></tr><tr><td>EX111</td><td>7:00 A.M.</td><td>55 min</td><td>7:55 A.M.</td><td>£20.00</td></tr><tr><td>RN902</td><td>8:30 A.M.</td><td>1 h 01 min</td><td>9:31 A.M.</td><td>£20.00</td></tr><tr><td>EX224</td><td>10:15 A.M.</td><td>1 h 15 min</td><td>11:30 A.M.</td><td>£18.00</td></tr><tr><td>RNS16</td><td>12:30 P.M.</td><td>1 h 25 min</td><td>1:55 P.M.</td><td>£18.00</td></tr><tr><td>EX670</td><td>2:00 P.M.</td><td>1 h 35 min</td><td>3:35 P.M.</td><td>£18.00</td></tr><tr><td>RN823</td><td>4:45 P.M.</td><td>1 h 05 min</td><td>5:50 P.M.</td><td>£20.00</td></tr></table><i>Purchasing tickets online at https://www.ntsrail.co.uk more than 24 hours before your trip entitles you to a 10 percent discount off the above-listed fares. Full-price tickets are available at all NTS Rail kiosks.</i>"
        ],
        questions: [
            { text: "Who most likely is Evrim Turgut?", options: { A: "A medical doctor", B: "An office manager", C: "A conference organizer", D: "A customer service representative" }, correct: "A", explanation: "Email nhắc đến việc Turgut và bác sĩ Williams cùng nghiên cứu công nghệ chẩn đoán hình ảnh y khoa ('your research together into diagnostic imaging technologies') -> Họ là bác sĩ." },
            { text: "What does the ticket indicate about Dr. Williams’ trip?", options: { A: "She will be traveling in first class.", B: "She will be changing trains during her trip.", C: "She will be using the same ticket for her return trip.", D: "She will be able to choose where to sit." }, correct: "D", explanation: "Trên vé tàu ghi 'Seat Number: NONE ASSIGNED' (Không chỉ định chỗ ngồi) -> Cô ấy có thể tự do chọn chỗ ngồi trên tàu." },
            { text: "Based on his availability, what train will Dr. Penfold most likely take?", options: { A: "EX111", B: "EX224", C: "RNS16", D: "RN823" }, correct: "D", explanation: "Trong Email, bác sĩ Penfold nói phải khám cho bệnh nhân đến 3 P.M. Đối chiếu với lịch trình, chuyến tàu duy nhất phù hợp (sau 3h chiều) là chuyến RN823 khởi hành lúc 4:45 P.M." },
            { text: "What is suggested about Dr. Williams?", options: { A: "She works in Manchester.", B: "She travels by train on a regular basis.", C: "She bought her ticket at a reduced price.", D: "She made her reservation at the Lancaster train station." }, correct: "C", explanation: "Vé của cô ấy ghi chuyến EX111 giá £18. Tuy nhiên trên bảng lịch trình, chuyến này có giá £20. Cô ấy được giảm 10% (xuống £18) nhờ mua vé Advance Purchase qua mạng trước ngày đi." },
            { text: "According to the schedule, what is true about the train trips?", options: { A: "They last the same length of time.", B: "They are cheaper in the morning.", C: "They will end at the same destination.", D: "They must be purchased in person." }, correct: "C", explanation: "Tiêu đề của lịch trình là 'Lancaster to Manchester' -> Tất cả các chuyến tàu đều kết thúc ở cùng một điểm đến là Manchester." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 8: Office supplies order
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>E-mail 1</b><br><b>To:</b> Imogen Chambers &lt;ichambers@championos.com&gt;<br><b>From:</b> Reginald Lee &lt;rlee@cooperandcolsonlaw.org&gt;<br><b>Re:</b> Office supplies order<br><b>Date:</b> March 20<br><br>Dear Ms. Chambers,<br><br>We have a standing order filled by Champion Office Supply, with automatic delivery to us on the first day of each month. I am writing because we would like to modify our usual order for the upcoming month as outlined in the attached form. Please note that we would like ink toner that we have ordered in the past to be replaced by a different brand as indicated. Furthermore, we would like to add item WB918 to the order only this month, as we have recently hired new attorneys and we are preparing additional office spaces for them. Please use our credit card account that you have on file.<br><br>We continue to be pleased with the quality of your merchandise, especially the recycled stationery products with our firm’s logo.<br><br>Thank you.<br>Reginald Lee, Office Manager<br>Cooper and Colson Law",

            "<b>Order Form</b><br><b>Order for:</b> Cooper and Colson Law<br><b>Contact:</b> Reginald Lee<br><b>Delivery date:</b> April 1<table border='1' cellpadding='8' style='border-collapse: collapse; width: 100%; margin: 15px 0; text-align: left; background-color: #fff;'><tr><th style='background-color: #f0f0f0;'>Item Description</th><th style='background-color: #f0f0f0;'>Item Number</th><th style='background-color: #f0f0f0;'>Quantity</th><th style='background-color: #f0f0f0;'>Price Per Unit</th><th style='background-color: #f0f0f0;'>Itemized Total</th></tr><tr><td>Printed letterhead</td><td>LH228</td><td>10 Reams</td><td>$54</td><td>$540</td></tr><tr><td>Whiteboard pens</td><td>WP263</td><td>10 Packages of 4</td><td>$4.99</td><td>$49.90</td></tr><tr><td>Cytronics ink toner cartridge</td><td>CPS76</td><td>8</td><td>$42</td><td>$336</td></tr><tr><td>Witeglow Magnetic Whiteboard (50\" x 35\")</td><td>WB918</td><td>4</td><td>$79.99</td><td>$319.96</td></tr></table><b>TAX:</b> $74.75<br><b>TOTAL:</b> $1320.61<br><br><i>Champion Office Supply</i>",

            "<b>E-mail 2</b><br><b>To:</b> Reginald Lee &lt;rlee@cooperandcolsonlaw.org&gt;<br><b>From:</b> Imogen Chambers &lt;ichambers@championos.com&gt;<br><b>Re:</b> Office supplies order<br><b>Date:</b> March 21<br><br>Dear Mr. Lee,<br><br>We would be happy to accommodate your requests as outlined on your order form. Unfortunately, however, we are currently out of the Witeglow brand whiteboards. I can recommend another brand of magnetic whiteboard that has been well liked by other customers, called Stellar Whiteboards. They are considered the best on the market. They are typically $85 each, but I am willing to provide four at the same cost of the Witeglow brand, if you would like to give them a try. Just let me know. Thank you.<br><br>Kind regards,<br>Imogen Chambers"
        ],
        questions: [
            { text: "What is the purpose of the first e-mail?", options: { A: "To amend a regular order", B: "To report a delivery error", C: "To make a complaint about a product", D: "To confirm a delivery date" }, correct: "A", explanation: "Email viết: 'we would like to modify our usual order' -> Muốn chỉnh sửa/bổ sung một đơn hàng thường xuyên." },
            { text: "In the first e-mail, what is indicated about Cooper and Colson Law?", options: { A: "It has just installed a new photocopier.", B: "It is currently expanding.", C: "It is in the process of relocating.", D: "It has just hired a new office manager." }, correct: "B", explanation: "Email 1 nhắc đến việc 'recently hired new attorneys and we are preparing additional office spaces' -> Vừa tuyển luật sư mới và đang chuẩn bị thêm không gian văn phòng -> Công ty đang mở rộng (expanding)." },
            { text: "What product is Mr. Lee particularly pleased with?", options: { A: "Paper with company letterhead", B: "Whiteboard pens", C: "The Witeglow magnetic whiteboard", D: "The Cytronics ink toner cartridge" }, correct: "A", explanation: "Cuối Email 1, Lee viết rất hài lòng với 'recycled stationery products with our firm’s logo' (sản phẩm văn phòng tái chế in logo công ty) -> Tương đương với giấy tiêu đề (letterhead)." },
            { text: "What item number identifies a replacement for a regularly ordered product?", options: { A: "LH228", B: "WP263", C: "CPS76", D: "WB918" }, correct: "C", explanation: "Email 1 ghi chú hộp mực in (ink toner) sẽ được đổi sang thương hiệu khác. Nhìn bảng đặt hàng, hộp mực mới là nhãn hiệu Cytronics có mã số CPS76." },
            { text: "How much will the law firm pay for each Stellar brand whiteboard?", options: { A: "$49.90", B: "$54.00", C: "$79.99", D: "$85.00" }, correct: "C", explanation: "Ở Email 2, nhà cung cấp hết bảng Witeglow nên gợi ý bảng Stellar và hứa bán bằng giá với Witeglow ('same cost of the Witeglow brand'). Đối chiếu bảng đặt hàng, bảng Witeglow có giá $79.99." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 9: Carson Office Supplies
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>Carson Office Supplies</b><br><b>SALE!</b><br><br>This weekend only, May 25–26, we're having our biggest sale of the year!<br><br><b>50% off</b> select printers<br><b>$15.99</b> for a 10-ream case of paper<br><b>25% off</b> all Sonama televisions<br><b>$150 off</b> all Rigukere office desks<br><b>$10 off</b> all Herbrot ink cartridges<br><br>Shop in store or online. Only while supplies last!",

            "<b>Carson Office Supplies</b><br><b>Return Authorization Request</b><br><br><b>Order Number:</b> 300034122<br><b>Account Number:</b> Business5271<br><b>Name:</b> Jane Mori<br><b>E-mail:</b> j.mori@welsomf.com<br><b>Subject:</b> Recent purchase<br><br><b>Reason for Return:</b><br>I am the purchasing manager at Welso Manufacturing, and we have a business account with Carson Office Supplies. Last week I purchased the following items: 3 Rigukere office desks, 15 Herbrot ink cartridges, 30 notepads, and 5 boxes of envelopes. Today I noticed in an advertisement for your upcoming weekend sale that some of the items I purchased are going to be heavily discounted. Would it be possible for me to get a refund for the applicable items and then rebuy them at the lower weekend sale price?",

            "<b>E-mail Response</b><br><b>To:</b> Jane Mori &lt;j.mori@welsomf.com&gt;<br><b>From:</b> Sheridan Homel &lt;shomel@cos.com&gt;<br><b>Date:</b> May 22<br><b>Subject:</b> Re: Exchange<br><b>Attachment:</b> Coupon, returns & exchanges<br><br>Dear Ms. Mori,<br><br>Thank you for your message and your continued business with Carson Office Supplies. Unfortunately, only items purchased on the official sale dates are eligible for the sale prices.<br><br>Because you have a business account with us, however, you automatically receive a 20 percent discount on bulk items (purchases of fifteen or more of the same item), which is deducted when you make a purchase through our online business portal. I can see from your order that this was the case for some of your items.<br><br>I can also offer you a 10 percent off coupon on your next purchase. The coupon is attached—it specifies the access code that you can use online. I will also attach our return and exchange procedures for your future reference.<br><br>Do not hesitate to contact me with any questions or concerns.<br><br>Sheridan Homel<br>Branch Manager<br>Carson Office Supplies"
        ],
        questions: [
            { text: "What is probably true about Ms. Mori?", options: { A: "She owns a business.", B: "She is a first-time customer.", C: "She received a discount on a printer.", D: "She purchased her items before May 25." }, correct: "D", explanation: "Đợt giảm giá (Sale) diễn ra vào ngày 25-26/5. Trong yêu cầu trả hàng, cô Mori nói đã mua hàng vào 'Last week' (tuần trước) -> Tức là cô mua hàng trước ngày 25/5." },
            { text: "Why does Ms. Mori ask about returning some of her items?", options: { A: "She received the wrong order.", B: "The items were broken when they arrived.", C: "The desks she ordered are too small.", D: "She wants to purchase items during the weekend sale." }, correct: "D", explanation: "Cô ấy muốn trả hàng để hoàn tiền, sau đó mua lại chính những món đó vào đợt giảm giá cuối tuần ('get a refund... and then rebuy them at the lower weekend sale price')." },
            { text: "According to the e-mail, why did Ms. Mori receive a discount on her bulk purchases?", options: { A: "She redeemed a coupon.", B: "She used a business account.", C: "She entered a special code online.", D: "She shopped during an exclusive sale for members." }, correct: "B", explanation: "Người quản lý phản hồi: 'Because you have a business account with us... you automatically receive a 20 percent discount on bulk items' -> Nhờ có tài khoản doanh nghiệp." },
            { text: "What items from Ms. Mori's purchase qualified for the bulk discount?", options: { A: "The office desks and notepads", B: "The ink cartridges and boxes of envelopes", C: "The ink cartridges and notepads", D: "The boxes of envelopes and the office desks" }, correct: "C", explanation: "Quy định giảm sỉ (bulk discount) là mua từ 15 sản phẩm CÙNG LOẠI trở lên. Đối chiếu với đơn hàng, cô ấy mua: 3 bàn, 15 hộp mực, 30 cuốn sổ, 5 hộp phong bì. Chỉ có hộp mực và sổ là đủ số lượng trên 15." },
            { text: "What was included with the e-mail?", options: { A: "An updated return form", B: "A document about store policy", C: "An application for a new account", D: "A receipt for Ms. Mori's purchase" }, correct: "B", explanation: "Quản lý viết: 'I will also attach our return and exchange procedures' -> Đính kèm quy trình (chính sách) đổi trả hàng của cửa hàng." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 10: Creative Tech Conference
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>Creative Tech Conference</b><br><br>Join us for the Tenth Annual Creative Tech Conference. Explore the latest technologies with the top innovators in their fields. Enjoy a full day of presentations, workshops, discussions, and exhibitions, culminating with a keynote address by Ayana Gonzalez, the founder of Grutenhur Tech.<br><br>May 12, 9 A.M.–6 P.M.<br>Bondal University<br>22 Markus Street<br>Ione, California<br><br>Purchase tickets online at www.creativetechcon.com/tickets.<br><i>Interested in being a sponsor? See the attached sponsor benefits brochure.</i>",

            "<b>Creative Tech Conference</b><br><b>Sponsor Benefits</b><br><br>We couldn’t run the Creative Tech Conference without the help of sponsors. In addition to supporting entrepreneurs and innovators, sponsorship is a great way to get the name of your business out to our 500+ attendees in various tech fields. See below for sponsorship levels.<br><br><b>Innovator — $5,000</b><br>Your company’s logo on a large banner displayed during the keynote address<br>Free four-hour exhibitor booth<br>Your company’s logo featured on our Web site and conference program<br>Half-price tickets for all employees that attend the conference<br><br><b>Creator — $3,000</b><br>Your company’s logo on a large banner displayed during the final reception<br>Free four-hour exhibitor booth<br>Your company’s logo featured on our Web site and conference program<br><br><b>Entrepreneur — $2,000</b><br>Your company’s logo featured on our Web site and conference program<br>Free four-hour exhibitor booth<br><br><b>Patron — $1,000</b><br>Your company’s logo featured on our Web site and conference program<br><br><i>Please contact sponsors@creativetechconference.com for more information.</i>",

            "<b>E-mail</b><br><b>To:</b> All Orlavel Analytics Staff<br><b>From:</b> Edsel Skyers<br><b>Subject:</b> Creative Tech Conference<br><b>Date:</b> May 2<br><br>Dear Staff,<br><br>I hope you will attend the Creative Tech Conference on May 12. It is taking place nearby at Bondal University. I have gone the past two years, and it is a great way to network and stay informed about the newest trends in our field. And because we are a sponsor of the event, our employees receive a discount on tickets. Plus, as some of you may know, the keynote speaker is a former employee! Let me know if you have any questions.<br><br>Edsel Skyers<br>Product Development Director<br>Orlavel Analytics"
        ],
        questions: [
            { text: "What does the invitation state about the Creative Tech Conference?", options: { A: "It is organized by university professors.", B: "University students can request free tickets.", C: "It is a one-day conference.", D: "This is the first year the conference will take place." }, correct: "C", explanation: "Quảng cáo ghi 'Enjoy a full day of presentations...' và lịch trình chỉ diễn ra trong đúng 1 ngày (May 12, 9 A.M.–6 P.M.)." },
            { text: "According to the brochure, what is a benefit of sponsoring the conference?", options: { A: "Sponsors can give a presentation at the conference.", B: "Sponsors are invited to a special reception.", C: "Sponsors can advertise their business to potential customers.", D: "Sponsors get free product samples." }, correct: "C", explanation: "Tờ rơi viết: 'sponsorship is a great way to get the name of your business out to our 500+ attendees' -> Giúp quảng bá công ty tới hơn 500 khách tham dự." },
            { text: "Why did Mr. Skyers write the e-mail?", options: { A: "To introduce his staff to a new employee", B: "To encourage his staff to attend an event", C: "To tell his staff about new technology", D: "To announce a research partnership with a university" }, correct: "B", explanation: "Mục đích của Edsel Skyers khi viết email là khuyên nhân viên đi dự hội nghị công nghệ ('I hope you will attend the Creative Tech Conference')." },
            { text: "What is indicated about Ms. Gonzalez?", options: { A: "She is a sponsor of the Creative Tech Conference.", B: "She lives in Ione, California.", C: "She opened a business 10 years ago.", D: "She previously worked for Orlavel Analytics." }, correct: "D", explanation: "Quảng cáo (đoạn 1) cho biết Ayana Gonzalez là diễn giả chính (keynote speaker). Email (đoạn 3) tiết lộ diễn giả chính từng là nhân viên cũ của Orlavel Analytics ('keynote speaker is a former employee')." },
            { text: "What type of sponsor is Orlavel Analytics?", options: { A: "Innovator", B: "Creator", C: "Entrepreneur", D: "Patron" }, correct: "A", explanation: "Email nhắc việc nhân viên công ty được giảm giá vé ('our employees receive a discount on tickets'). Đối chiếu với bảng gói tài trợ, chỉ có gói Innovator mới có quyền lợi 'Half-price tickets for all employees'." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 11: Wonder Ridge Radio
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>Wonder Ridge Radio Broadcast Schedule, Monday–Friday</b><table border='1' cellpadding='8' style='border-collapse: collapse; width: 100%; margin: 15px 0; text-align: left; background-color: #fff;'><tr><th style='background-color: #f0f0f0;'>Time</th><th style='background-color: #f0f0f0;'>Program</th><th style='background-color: #f0f0f0;'>Description</th><th style='background-color: #f0f0f0;'>Host</th></tr><tr><td>6 A.M.–Noon</td><td>COFFEE BREAK</td><td>Local news and interviews with community members</td><td>Felice Finney</td></tr><tr><td>Noon–4 P.M.</td><td>AFTERNOON JAZZ</td><td>Music from traditional jazz to jazz fusion</td><td>Malachi Mize</td></tr><tr><td>4 P.M.–7 P.M.</td><td>FOLK FRENZY</td><td>Folk music from around the world</td><td>Penny Ariza</td></tr><tr><td>7 P.M.–10 P.M.</td><td>JOSIE’S JOINT</td><td>Modern sounds selected by our station’s own music director</td><td>Josie Jones</td></tr></table>",

            "<b>E-mail</b><br><b>To:</b> feedback@wonderridgeradio.org<br><b>From:</b> pfabre@sendmail.net<br><b>Subject:</b> My new radio station!<br><b>Date:</b> October 22<br><br>To the folks at Wonder Ridge Radio:<br><br>As I was driving last week, I got tired of listening to sports talk and turned the dial. Suddenly, my car was filled with a song that I hadn’t heard in many years. It was traditional music from France, where my grandmother was born. She used to play that song when I was a child. I never expected to hear it on the radio here in Wonder Ridge. Thanks for this experience and for all your great programs.<br><br>Your new fan,<br>Pierre Fabre",

            "<b>Wonder Ridge Radio Job Opening: Programming Assistant</b><br><b>Posted November 2</b><br><br><b>Job Description</b><br>The programming assistant reports to the director of programming and supports the radio station by performing a variety of research and communication functions. This role is entry-level, part-time position.<br><br><b>Responsibilities</b><br>- Conducting background research on interviewees<br>- Keeping up-to-date on news and news makers in order to suggest potential topics and guests for on-air interviews<br>- Updating the station’s Web site and program host biography pages<br>- Using scheduling software to update the broadcast schedule<br>- Communicating with listeners, especially via e-mail and social media<br><br><i>To apply, e-mail a résumé and cover letter to hiring@wonderridgeradio.org.</i>"
        ],
        questions: [
            { text: "According to the schedule, who is Ms. Jones?", options: { A: "The advertising manager at a radio station.", B: "The host of a community news program.", C: "The music director at Wonder Ridge Radio.", D: "The host of a sports radio program." }, correct: "C", explanation: "Lịch trình mục 7 P.M. ghi người dẫn chương trình Josie Jones mở nhạc do 'our station’s own music director' lựa chọn. Thực chất vì show tên là 'JOSIE'S JOINT' nên Josie chính là giám đốc âm nhạc." },
            { text: "What is the purpose of the e-mail?", options: { A: "To express praise for the radio station.", B: "To ask about job opportunities.", C: "To request more sports talk show programming.", D: "To inquire about the name of a song." }, correct: "A", explanation: "Email kết thúc bằng câu 'Thanks for this experience and for all your great programs' -> Cảm ơn và khen ngợi đài phát thanh." },
            { text: "When did Mr. Fabre most likely first listen to Wonder Ridge Radio?", options: { A: "Between 6 and noon.", B: "Between noon and 4.", C: "Between 4 and 7.", D: "Between 7 and 10." }, correct: "C", explanation: "Ông Fabre nghe được 'traditional music from France' (nhạc truyền thống Pháp). Thể loại này thuộc nhóm nhạc dân gian thế giới (Folk music from around the world), phát sóng ở chương trình FOLK FRENZY lúc 4 P.M.–7 P.M." },
            { text: "What does the job advertisement suggest applicants must have?", options: { A: "A willingness to travel.", B: "Familiarity with computers.", C: "A degree in communications.", D: "Extensive experience in the radio industry." }, correct: "B", explanation: "Trách nhiệm công việc có yêu cầu 'Updating the station’s Web site', 'Using scheduling software' -> Cần phải thành thạo sử dụng máy tính." },
            { text: "What radio program will probably receive the most support from the programming assistant?", options: { A: "Coffee Break", B: "Afternoon Jazz", C: "Folk Frenzy", D: "Josie’s Joint" }, correct: "A", explanation: "Trợ lý phải làm nhiệm vụ 'Conducting background research on interviewees' (nghiên cứu người được phỏng vấn). Nhìn lên lịch, chương trình duy nhất có phỏng vấn (interviews) là Coffee Break." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 12: Requesting Records
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>Instructions for Requesting Records</b><br><br>Thank you for your interest in official records and documents maintained by the City of Abilene. To file a request for public information, please follow these steps.<br><br>1. Create an account in the Records Center Web portal. Currently, all requests must be made through the portal.<br>2. Use the drop-down menu to locate the department from which you are seeking information and submit your request. You will receive a confirmation e-mail with a reference number.<br>3. The department staff will locate the requested records and contact you when they are available. You can have the records delivered to you, or you can pick them up in person. If you prefer to pick them up in person, you must make an appointment with the department staff.<br>4. If there are any fees associated with your request, you will receive an itemized statement detailing the services provided and the charges for those specific services.",

            "<b>E-Mail Message</b><br><b>To:</b> Joo-Hee Park &lt;jhpark@coa.net&gt;<br><b>From:</b> Keith Brandenberg &lt;kbrandenberg@mailcurrent.com&gt;<br><b>Date:</b> May 3<br><b>Subject:</b> RE: Reference number W2486<br><br>Dear Ms. Park,<br><br>Thank you for confirming that my documents are available. I would like to pick them up in person as soon as possible. Do you have any appointments available this week?<br><br>I have a question about the fee. Apparently, I am being charged $300 for my documents. I do not understand why the fee is so high, and there was no explanation included in your e-mail. I have requested records several times in the past in my role with RJ Environmental Engineering and have never paid such a high fee. In this case, I am only requesting two maps of the city’s underground pipelines, which will inform our firm’s current work advising the city on wastewater management.<br><br>Please clarify the fee for me, and let me know if I can pick up my documents this week. Thank you.<br><br>Best regards,<br>Keith Brandenberg",

            "<b>City of Abilene Administrative Building</b><br><br><i>Visitors must sign in prior to entering this facility. Please enter your name and the room you will visit in the logbook.</i><br><br><b>First-Floor Directory:</b><br>IT Services – Room 100<br>Parks and Recreation – Room 101<br>Transportation – Room 102<br>Wastewater – Room 103"
        ],
        questions: [
            { text: "What do the instructions indicate about records requests?", options: { A: "They can be made only on certain days.", B: "They can be made only online.", C: "They can be filed only by authorized personnel.", D: "They can be filed only after a fee is paid." }, correct: "B", explanation: "Mục 1 của Hướng dẫn ghi rõ 'all requests must be made through the portal' -> Tất cả các yêu cầu phải làm trên cổng thông tin mạng (online)." },
            { text: "According to the e-mail, how does Mr. Brandenberg plan to use some public information?", options: { A: "To add information to a Web portal.", B: "To help his company advise the city.", C: "To identify an accounting error.", D: "To learn how an agency is structured." }, correct: "B", explanation: "Ông ấy viết 'inform our firm’s current work advising the city' -> Dùng bản đồ để giúp công ty của ông ấy tư vấn cho thành phố." },
            { text: "What does the sign indicate visitors must do before entering a building?", options: { A: "Go through a security screening.", B: "Get a parking permit.", C: "Present some identification.", D: "Sign a logbook." }, correct: "D", explanation: "Biển báo quy định 'Visitors must sign in prior to entering this facility... enter your name... in the logbook' -> Khách phải ký vào sổ đăng ký (logbook)." },
            { text: "What was Mr. Brandenberg expecting to receive?", options: { A: "An itemized statement of fees.", B: "A letter from his company.", C: "A phone call from a city official.", D: "A password for the Web portal." }, correct: "A", explanation: "Theo mục số 4, nếu bị thu phí thì người nộp đơn sẽ nhận được bản sao kê chi tiết (itemized statement). Trong Email, ông ấy thắc mắc tại sao bị thu $300 mà lại không nhận được 'explanation' (lời giải thích/bản sao kê) nào." },
            { text: "What room will Mr. Brandenberg most likely visit?", options: { A: "Room 100", B: "Room 101", C: "Room 102", D: "Room 103" }, correct: "D", explanation: "Trong Email, ông Brandenberg nói ông ấy xin tài liệu liên quan đến 'wastewater management' (quản lý nước thải). Dựa vào Bảng chỉ dẫn, phòng Wastewater nằm ở Room 103." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 13: Famous Actor, First Book
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>Famous Actor, First Book</b><br><b>LONDON (25 February)</b>—Fans of Simon Eklund will be delighted with his autobiography, The Theatre Lights Dimmed, the first book he has written in his storied career as an actor. It provides wonderful insight into his career, starting with his first roles in cinema in his native Sweden, moving into his work in France and Italy, and finishing with his recent theatre work in the U.K.<br><br>In his book, Mr. Eklund dedicates a fair amount of text to discussing his mentor, Charles Gunnarsson, who helped him develop his skills early on in Stockholm. He also describes the difficulty of transitioning into different types of roles, especially from comedic to dramatic acting. He includes several funny anecdotes about his first attempts at acting onstage here in London. He describes them as disastrous, but anyone who saw his recent performance in Life and Games would say just the opposite.<br><br>Mr. Eklund has long been a captivating actor on stage and screen, and now he is a thoroughly engaging author.<br><br>—Uma Joshi",

            "<b>E-mail 1</b><br><b>To:</b> Edith Hocking<br><b>From:</b> Uma Joshi<br><b>Date:</b> 2 March<br><b>Subject:</b> RE: Opportunity<br><br>Dear Edith,<br><br>Thank you for agreeing to arrange an interview with Mr. Eklund for me. I think this will be a great follow-up to my recent piece.<br><br>In a helpful coincidence, I will be visiting his home country next month to address a journalists’ convention. I am the featured speaker and will discuss the benefits of diversity in journalism. I’m sure we can set up something with Mr. Eklund just before or after my speech.<br><br>Best,<br>Uma Joshi<br>Arts and Culture Editor<br>Top News U.K.",

            "<b>E-mail 2</b><br><b>To:</b> Uma Joshi &lt;ujoshi@topnews.co.uk&gt;<br><b>From:</b> Maria Cazalla &lt;mcazalla@zephyrmail.se&gt;<br><b>Date:</b> 20 March<br><b>Subject:</b> RE: Information<br><br>Dear Ms. Joshi,<br><br>We are all very excited about your interview next month with Mr. Eklund. He enjoys all your writing for Top News U.K.—the news stories, interviews, and, of course, your recent article about The Theatre Lights Dimmed.<br><br>I just wanted to finalize a few details with you. We have arranged transportation for you from your hotel to Mr. Eklund’s house and then back to the hotel. Please let me know how many people there will be in your group, because Mr. Eklund would like you all to stay for lunch.<br><br>Sincerely,<br>Maria Cazalla"
        ],
        questions: [
            { text: "What does the review mention about Mr. Eklund?", options: { A: "He enjoys his work as a director.", B: "He has been a mentor to many young people.", C: "He is a well-known actor.", D: "He has written many books." }, correct: "C", explanation: "Bài báo viết ông ấy có 'storied career as an actor' và 'captivating actor' -> Là một nam diễn viên nổi tiếng." },
            { text: "Where most likely will Ms. Joshi meet Mr. Eklund?", options: { A: "In Sweden", B: "In France", C: "In Italy", D: "In the United Kingdom" }, correct: "A", explanation: "Email 1 nói Joshi sẽ đến thăm quê nhà của ông ấy ('home country'). Bài review báo cho biết Eklund sinh ra ở Thụy Điển ('his native Sweden') -> Cô ấy sẽ gặp ông ở Thụy Điển." },
            { text: "According to the first e-mail, what is one reason Ms. Joshi will travel in April?", options: { A: "To go on a vacation", B: "To interview for a new job", C: "To attend an international film festival", D: "To speak at a conference" }, correct: "D", explanation: "Email 1 cô ấy viết: 'address a journalists’ convention. I am the featured speaker' -> Diễn thuyết tại một hội nghị nhà báo." },
            { text: "What is the purpose of the second e-mail?", options: { A: "To reserve a hotel room", B: "To confirm meeting arrangements", C: "To discuss an idea for a movie", D: "To ask for transportation" }, correct: "B", explanation: "Người trợ lý viết email để 'finalize a few details' (chốt lại vài chi tiết) như phương tiện đi lại, số người đi cùng, bữa trưa -> Để xác nhận sự sắp xếp cho cuộc hẹn (confirm meeting arrangements)." },
            { text: "What can be concluded about Mr. Eklund?", options: { A: "He hopes to write for a British news site.", B: "He just hired a new assistant.", C: "He was pleased with Ms. Joshi’s review of his book.", D: "He frequently cooks special meals." }, correct: "C", explanation: "Email 2 nói ông Eklund rất thích bài báo gần đây của cô Joshi về The Theatre Lights Dimmed. Bài báo đầu tiên chính là một bài review ngợi khen cuốn sách này do chính Joshi viết. -> Suy ra ông ấy rất hài lòng với bài đánh giá sách của cô." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 14: Job tip
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>E-mail 1</b><br><b>To:</b> jsantos@coloniamenor.com<br><b>From:</b> markash@amtrcorp.com<br><b>Date:</b> September 4<br><b>Subject:</b> Job tip<br><br>Hello, Juan,<br><br>It was nice to see you again at the Tech Writers’ Conference in Mexico City. You mentioned that your cousin Carlos Cruz wants to find a product design job here in Dallas. Well, the company I work for, AMTR Corporation, is about to post a job for a junior industrial designer, which might interest him. So far, the company has announced the opening only to current employees, but next week it will appear on the company Web site. The salary is good, and there may not be any qualified candidates in-house. Please let him know about this opportunity.<br><br>Heide Markas",

            "<b>Web Page</b><br><b>AMTR Corporation – Careers – Current Opportunities</b><br><br><b>Junior Industrial Designer:</b> This is a full-time position developing and improving the full range of products manufactured by AMTR Corporation in Dallas, Texas.<br><br><b>Sample Job Duties:</b><br>- Design consumer and office supply products, including personal computers, tablets, copiers, and printers<br>- Collaborate with design team and colleagues from engineering, marketing, and manufacturing departments to develop new products<br>- Improve sustainability efforts by promoting the use of recycled, recyclable, and reusable materials<br><br><b>Qualifications:</b><br>- Understanding of design principles, theories, and concepts<br>- Ability to analyze and apply customer feedback<br>- Proven analytical and problem-solving skills<br>- Experience in creating sketches, storyboards, models, and prototypes<br>- Bachelor’s or master’s degree in industrial design",

            "<b>E-mail 2</b><br><b>To:</b> Carlos Cruz &lt;ccruz@mail.com&gt;<br><b>From:</b> Pamela Wang &lt;wangp@amtrcorp.com&gt;<br><b>Date:</b> November 11<br><b>Subject:</b> Job Application<br><br>Dear Mr. Cruz,<br><br>Thank you for submitting your application for junior industrial designer at AMTR Corporation. Our hiring committee has reviewed your application and determined that you meet the qualifications for the position. We will contact you shortly to schedule an initial interview. Interviews will be held on-site at our Dallas headquarters during the first two weeks of December. In the meantime, you will receive a request for professional references via e-mail. Please respond to the request as soon as you receive it.<br><br>Cordially,<br>Pamela Wang<br>Human Resources Specialist<br>AMTR Corporation"
        ],
        questions: [
            { text: "What is the purpose of the first e-mail?", options: { A: "To share information about a new job opening", B: "To ask whether a company is hiring new staff", C: "To learn whether a colleague will attend an upcoming conference", D: "To congratulate someone for getting a new job" }, correct: "A", explanation: "Heide viết email báo cho bạn mình về vị trí 'junior industrial designer' sắp được đăng tuyển tại công ty của cô ấy -> Chia sẻ thông tin về việc làm mới." },
            { text: "What does the company that Ms. Markas works for produce?", options: { A: "Guides for creating Web sites", B: "Operating manuals for passenger airplanes", C: "Transportation system maps", D: "Office equipment" }, correct: "D", explanation: "Email 1 cho biết Markas làm việc tại AMTR Corporation. Trên trang Web, AMTR được mô tả là thiết kế máy tính cá nhân, máy tính bảng, máy photocopy và máy in ('copiers, and printers') -> Thiết bị văn phòng." },
            { text: "What is explained in the second e-mail?", options: { A: "The procedure for submitting an application", B: "What applicants can expect during an interview", C: "The next steps of the hiring process", D: "AMTR Corporation’s expectations for designers" }, correct: "C", explanation: "Email của chuyên viên nhân sự hướng dẫn Carlos các bước tiếp theo: lên lịch phỏng vấn vòng 1, chờ email yêu cầu thư giới thiệu -> Giải thích các bước tiếp theo trong quy trình tuyển dụng." },
            { text: "What will AMTR Corporation do during the first two weeks of December?", options: { A: "Move its headquarters to Dallas", B: "Begin reviewing applications", C: "Send out professional references", D: "Perform the first round of interviews" }, correct: "D", explanation: "Email 2 viết: 'Interviews will be held on-site... during the first two weeks of December' -> Diễn ra vòng phỏng vấn đầu tiên." },
            { text: "What is most likely true about Mr. Cruz?", options: { A: "He will begin the job in November.", B: "He has a degree in industrial design.", C: "He has relocated to Dallas.", D: "He recently interviewed for a new job." }, correct: "B", explanation: "Email 2 xác nhận anh ấy ĐÁP ỨNG ĐỦ tiêu chuẩn ('meet the qualifications'). Nhìn vào Web Page, điều kiện bắt buộc là phải có bằng Cử nhân hoặc Thạc sĩ ngành thiết kế công nghiệp -> Anh ấy phải có bằng cấp này." }
        ]
    },

    // ==========================================
    // BÀI ĐỌC SỐ 15: Shingle Town Roofing
    // ==========================================
    {
        type: "Triple Passage",
        texts: [
            "<b>Shingle Town Roofing</b><br><b>Color Options</b><br><br>Choose from our many colors of high-quality, affordable shingles for a long-lasting, beautiful roof.<br><br><b>Color - Product Number</b><br>Lawnwood Blue (#302)<br>Charcoal Bliss (#702)<br>Foxwood Gray (#704)<br>Mission Gray (#707)<br>Cedarwood (#203)<br>Hickory Nut (#209)<br>Brick Red (#505)",

            "<b>Letter</b><br>Joanne Westley<br>8021 Daffodil Lane<br>Herndon, Virginia 22090<br><br>Dear Ms. Westley,<br><br>This is to confirm our agreement to replace your roof in Herndon, Virginia, on August 4. As discussed, we will be using our exclusive Prime Technology System with Hickory Nut color shingles. The Prime Technology System is guaranteed to keep your house dry and has a ten-year warranty for labor and materials.<br><br>Our crew will arrive at 8:30 A.M. We have received your deposit and signed contract. The remainder of the charge is due upon completion of the job. Please contact us if you have any questions.<br><br>Martin Sage<br>Customer service representative<br>Shingle Town Roofing",

            "<b>Shingle Town Roofing: Installation Schedule for August 1–7</b><br><i>Note to installation crew: Be sure to confirm the job location and the required materials.</i><table border='1' cellpadding='8' style='border-collapse: collapse; width: 100%; margin: 15px 0; text-align: left; background-color: #fff;'><tr><th style='background-color: #f0f0f0;'>Sunday</th><th style='background-color: #f0f0f0;'>Monday</th><th style='background-color: #f0f0f0;'>Tuesday</th><th style='background-color: #f0f0f0;'>Wednesday</th><th style='background-color: #f0f0f0;'>Thursday</th><th style='background-color: #f0f0f0;'>Friday</th><th style='background-color: #f0f0f0;'>Saturday</th></tr><tr><td>1</td><td>2<br>Harris residence (#702)</td><td>3<br>Landsford Apartments E-3 (#505)</td><td>4<br>Westley residence (#209)</td><td>5<br>Kendelwood Motel (#302)</td><td>6<br>Hopewell Gardens (#704)</td><td>7<br>Hopewell Gardens (#704)</td></tr></table>"
        ],
        questions: [
            { text: "What is the purpose of the letter?", options: { A: "To get a cost estimate for a new roof", B: "To request a deposit for a job", C: "To ask a contractor to do a project", D: "To finalize a business arrangement" }, correct: "D", explanation: "Martin Sage viết thư 'to confirm our agreement' (để xác nhận thỏa thuận) và thông báo đã nhận cọc, đã ký hợp đồng -> Mục đích là để chốt lại/hoàn tất một thỏa thuận kinh doanh." },
            { text: "What does Mr. Sage indicate about the Prime Technology System?", options: { A: "It requires a separate fee for the ten-year warranty.", B: "It prevents water from leaking into a house.", C: "It is available for only certain types of shingles.", D: "It requires a large crew to install." }, correct: "B", explanation: "Bức thư cam kết hệ thống này 'guaranteed to keep your house dry' (đảm bảo giữ nhà bạn khô ráo) -> Nó giúp ngăn nước rò rỉ vào nhà." },
            { text: "Where is a shingles installation scheduled to take place on August 3?", options: { A: "At the Harris residence", B: "At Landsford Apartments", C: "At Kendelwood Motel", D: "At Hopewell Gardens" }, correct: "B", explanation: "Tra cứu trong bảng lịch trình thi công, ngày mùng 3 (Tuesday 3) ghi địa điểm là 'Landsford Apartments E-3'." },
            { text: "What color shingles will the crew be installing at Kendelwood Motel?", options: { A: "Lawnwood Blue", B: "Charcoal Bliss", C: "Mission Gray", D: "Brick Red" }, correct: "A", explanation: "Lịch trình ghi Kendelwood Motel sử dụng mã vật liệu #302. Gióng lên bảng Mã màu (Color Options), #302 tương ứng với màu 'Lawnwood Blue'." },
            { text: "When will Shingle Town Roofing do work at 8021 Daffodil Lane?", options: { A: "On Monday", B: "On Tuesday", C: "On Wednesday", D: "On Thursday" }, correct: "C", explanation: "Khách hàng Joanne Westley ở địa chỉ 8021 Daffodil Lane. Thư xác nhận thi công cho nhà cô ấy vào ngày August 4 (mùng 4 tháng 8). Tra trên lịch trình, ngày mùng 4 là thứ Tư (Wednesday)." }
        ]
    }
];